name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Terraform command'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - plan
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform

      - name: Run Terraform command
        run: terraform ${{ github.event.inputs.command }} -auto-approve
        working-directory: ./terraform
